Issue #1 Github로그인 기능 구현~~
code-squad/woowahan-2018 pull request #23
Opened 2018-02-19 10:54 UTC by HannaJeon

이슈번호 #1 기능 구현

2018-02-19 10:59 UTC, skim451 requested changes

2018-02-19 10:59 UTC, skim451 commented on src/main/java/com/woowahan/woowahan2018/config/WebMvcConfig.java
> +        registry.addInterceptor(basicAuthInterceptor());
빼주세영

2018-02-19 10:59 UTC, skim451 commented on src/main/java/com/woowahan/woowahan2018/config/WebMvcConfig.java
> +    public BasicAuthInterceptor basicAuthInterceptor() {
이것두

2018-02-19 10:59 UTC, skim451 commented on src/main/java/com/woowahan/woowahan2018/domain/User.java
> +import javax.persistence.*;
.* import는 지양해야한다고 생각함미다

2018-02-20 01:34 UTC, Jeju-Boobby commented on src/main/resources/static/login.html
> +<!--<script type="text/javascript" src="./js/githubConfig.js"></script>-->
이 주석은 없어도 되는건가요?

2018-02-20 01:34 UTC, smartyjpark commented on src/main/resources/static/login.html
> +  <a class="github-login waves-effect waves-light btn" href="/login/github">
요청 경로가 api/users/login/github 이런식으로 되어야 하지 않을까요?

2018-02-20 02:19 UTC, crongro requested changes
JS코드에서, 
데이터는 하드코딩하지 말기~

2018-02-20 02:19 UTC, crongro commented on src/main/resources/static/js/githubLogin.js
> +    const width = 500
가급적 이런 하드코딩된 숫자는 지양하는게 좋을 거 같아요.
예를들어, 500과 800은 어떤 계산과정에 의해서 알아낼 수 있다면 좋겠네요.

2018-02-20 02:19 UTC, crongro commented on src/main/resources/static/js/githubLogin.js
> +    window.open("http://localhost:8080/login", "githubLogin", "width="+width+", height="+height+", top="+top+", left="+left);
이런 url정보도 하드코딩하지 말고, 인자로 받던가 하세요.

2018-02-20 02:23 UTC, HannaJeon commented on src/main/java/com/woowahan/woowahan2018/config/WebMvcConfig.java
> +        registry.addInterceptor(basicAuthInterceptor());
뺌

2018-02-20 02:23 UTC, HannaJeon commented on src/main/java/com/woowahan/woowahan2018/config/WebMvcConfig.java
> +    public BasicAuthInterceptor basicAuthInterceptor() {
뺌

2018-02-20 02:24 UTC, HannaJeon commented on src/main/java/com/woowahan/woowahan2018/domain/User.java
> +import javax.persistence.*;
노력했으나 실패

2018-02-20 02:25 UTC, HannaJeon commented on src/main/resources/static/login.html
> +<!--<script type="text/javascript" src="./js/githubConfig.js"></script>-->
안되요오.. 일단 깃헙 로그인 시도할 때 페이지 이동되는 걸로 적용되어있는데 추후에 modal형식으로 바꾸고싶은 욕심이 있습니다

2018-02-20 02:27 UTC, HannaJeon commented on src/main/resources/static/login.html
> +  <a class="github-login waves-effect waves-light btn" href="/login/github">
파.워.당.당

2018-02-20 03:03 UTC, merged