Feature card functions #43
code-squad/woowahan-2018 pull request #61
Opened 2018-02-28 11:10 UTC by Jeju-Boobby

카드 기능구현 완료했습니다!!

2018-02-28 13:38 UTC, javajigi requested changes
피드백 남겨요.

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/controller/CardController.java
> +        });
이 로직은 card에 구현하는 것이 낫지 않을까요?

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/domain/Card.java
> +        this.description = cardDto.getDescription();
누구나 수정할 수 있는 건가요?

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/domain/Card.java
> +        this.dueDate = cardDto.getDueDate();
누구나 수정할 수 있는 건가요?

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/domain/Deck.java
> +        return cards.getCards();
굳이 List<Card>로 반환하지 않고 Cards를 반환하면 안되나?

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/service/CardService.java
> +        cardDto.setDescription(description);
굳이 CardDto에 담는 이유는?

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/service/CardService.java
> +        cardDto.setDueDate(dueDate);
굳이 CardDto에 담는 이유는?

2018-02-28 13:38 UTC, javajigi commented on src/main/java/com/woowahan/woowahan2018/domain/Deck.java
> +    }
위 두 개의 sort() 메소드를 Cards로 이동할 수는 없을까?

2018-03-01 05:46 UTC, crongro approved these changes
webpack으로 bundle 할때, 
dev 모드랑, production 모드를 어떻게 나누는지 학습해두세요. 실무에서 webpack쓸때 기본이고 가장 중요한 부분이에요. 
production에서는 코드를 압축하고, sourcemap(디버깅용)을 안쓰고 배포하도록 webpack구성을 해야합니다.

비동기 작업은 이제는 async/await 를 많이 쓰긴 합니다. 
generator라는 방법도 있으니 찾아보세요.(coroutine기법)
rxjs를 공부하는 것도 좋은 방법.

요즘 프레임워크를 사용하면서, 함수형개념으로 많이 코딩해요. 
foreach/filter/reduce 와 같은 것뿐아니라, 함수합성, pipeline방식등도 알아보세요. 

점차 가벼운 프레임워크가 등장하고 인기를 얻을 겁니다. angular와 같은 것은 점점 없어질 거에요. 사내에서도 가벼운 프레임워크 구조를 가지려고 노력하세요. 자체적으로 개발중인 것도 띠었다 붙였다 할 수 있도록 아키텍쳐를 만들어야하고요.  state management가 필수가 아닙니다.(redux같은) 따라서 컴포넌트별로 state management를 하는 간단한 구조를 실무에 쓰는게 더 유지보수하기 좋을 겁니다. 

UI테스팅은 아주 힘들고 어려운 일입니다.  단위테스트부터 꾸준히 해보도록 하세요. Jest나 jasmine이 실무에 도입할만합니다. 하지만 테스트는  도구가 중요한게 아니고 의지가 중요합니다. 

실무를 한다고 성장이 그냥 되는게 아닙니다.
공부는 따로 한다고 생각하고 꾸준히 무언가를 학습하셔야 할거에요. 시키는 것만 하면 당장성과는 좋지만 몇년뒤 내가 약해집니다.

2018-03-01 05:46 UTC, crongro commented on src/main/resources/static/js/board/CardModalHandler.js
> +        const comment = res.content;
함수의 파라미터를 전달받을 때 destructuring을 사용할 수도 있어요.

2018-03-01 05:46 UTC, crongro commented on src/main/resources/static/js/board/CardModalHandler.js
> +                }
참고로 filter메서드와 forEach를 섞어서 쓸 수도 있겠군요.

2018-03-01 05:46 UTC, nigayo commented on src/main/resources/static/js/board/CardModalHandler.js
> +            if (e.target.classList.contains("close-modal")) {
조건문이 많고 복잡해보여요.
여러가지 조건상황이 있을 수 있는 건 어쩔 수 없을거 같네요.
그럼에도 개선할 것들을 고민해봐야겠어요.

var classObj = e.target.classList;  //이렇게 객체를 지역변수화 시켜서 간결하고 성능도 더 좋게하고요. 
아니면   e.target.classList.contains(name); 코드를 많이 사용하니까 이녀석을 함수화시켜서 불러서 사용하는 것도 좋겠고요.
else if (_contains("card-edit-close")) {}

2018-03-01 05:46 UTC, nigayo commented on src/main/resources/static/js/board/CardModalHandler.js
> +        _.$(".assignees-list").innerHTML += members.reduce((html, member) => {
reduce 는 막강해요. 
template작업할때 기억해서 자주 써먹으면 꿀.

2018-03-01 06:17 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/controller/CardController.java
> +        });
card의 내용을 수정하는게 아니라 밖으로 뺐는데 service에서 처리하는게 나을거 같네요..

2018-03-01 06:19 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/domain/Card.java
> +        this.description = cardDto.getDescription();
서비스단에서 권한 체크하고 있는데.. card에서 해주는게 나을거 같네요

2018-03-01 06:19 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/domain/Card.java
> +        this.dueDate = cardDto.getDueDate();
서비스단에서 권한 체크하고 있는데.. card에서 해주는게 나을거 같네요

2018-03-01 06:20 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/domain/Deck.java
> +        return cards.getCards();
반영하겠습니다~

2018-03-01 06:21 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/service/CardService.java
> +        cardDto.setDescription(description);
바로 set 하기 꺼림찍해서 dto로..하하

2018-03-01 06:22 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/service/CardService.java
> +        cardDto.setDueDate(dueDate);
이것도 꺼림찍해서..

2018-03-01 06:33 UTC, smartyjpark commented on src/main/resources/static/js/board/CardModalHandler.js
> +        _.$(".assignees-list").innerHTML += members.reduce((html, member) => {
정말 템플릿 작업에서 reduce는 축복으로 느껴집니다 ㅎㅎ 더 적극적으로 활용해보겠습니다!

2018-03-01 06:37 UTC, smartyjpark commented on src/main/resources/static/js/board/CardModalHandler.js
> +            if (e.target.classList.contains("close-modal")) {
사실 이벤트핸들러를 적용시키면서 e.target.classList.contains()를 그냥 쓰는데 익숙해진 것 같습니다. 이렇게 반복되는 부분은 함수로 빼놓겠습니다!

2018-03-01 06:42 UTC, smartyjpark commented on src/main/resources/static/js/board/CardModalHandler.js
> +        const comment = res.content;
destructuring을 배워놓고 활용할 생각을 못했었습니다... ㅠㅠ 적용해보겠습니다!

2018-03-01 06:45 UTC, smartyjpark commented on src/main/resources/static/js/board/CardModalHandler.js
> +                }
이부분은 확실히 filter를 활용하는게 맞겠군요! 적용해보겠습니다!

2018-03-02 01:57 UTC, Jeju-Boobby commented on src/main/java/com/woowahan/woowahan2018/domain/Deck.java
> +        return cards.getCards();
Cards로 변경하고 나서 테스트해보니 json구조가 바뀌면서 cards.cards 라는 형태로 나와서
다시 롤백했습니다.

2018-03-02 02:03 UTC, smartyjpark commented on src/main/resources/static/js/board/CardModalHandler.js
> +        const comment = res.content;
적용했습니다!

2018-03-02 02:41 UTC, smartyjpark commented on src/main/resources/static/js/board/CardModalHandler.js
> +                }
filter나 foreach를 돌리지 않아도 되는 부분인걸 확인하고 수정하였습니다!

2018-03-02 03:02 UTC, javajigi approved these changes

2018-03-02 03:02 UTC, merged